@endpoint = http://localhost:8080

  #@endpoint = https://house.cloud.smallsaas.cn/


### 手动同步
PUT {{endpoint}}/api/crud/frontPageModuleInfo/synchronizationData?moduleType=autolist


### 分页
# moduleType 模组类型
# synchronization为false表示不同步（同步：从动态页面配置表获取数据同步到临时表） 可选 默认为true
GET  {{endpoint}}/api/crud/frontPageModuleInfo?synchronization=true&moduleType=autolist


### 分页 终端用户接口
# moduleType 模组类型
# synchronization为false表示不同步（同步：从动态页面配置表获取数据同步到临时表） 可选 默认为true
GET  {{endpoint}}/api/u/frontPageModuleInfo?synchronization=true&moduleType=autolist






### 动态页面 tag测试



GET  {{endpoint}}/api/u/frontPage/frontPage/frontPages/102



### 动态页面 列表

GET  {{endpoint}}/api/u/frontPage/frontPage/frontPages?tagName=房屋管理

### 动态页面 tag测试


Put  {{endpoint}}/api/u/frontPage/frontPage/frontPages/102

 {
        "appid": "DEFAULT",
        "content": "{\"name\": \"assetListing\", \"title\": \"房源上架\", \"loadApi\": \"\", \"modules\": [{\"key\": \"e6b14b71-1759-455c-b8fd-7f7349ef3311\", \"name\": \"列表\", \"type\": \"autolist\", \"container\": {\"height\": \"\", \"background\": \"\"}}], \"request\": {}, \"version\": \"1\", \"response\": {\"data\": \"data\"}, \"pageStyle\": {}, \"moduleData\": {\"e6b14b71-1759-455c-b8fd-7f7349ef3311\": {\"jump\": true, \"jumpUrl\": \"/rentHouse/addAvailableHouse\", \"loadApi\": \"/api/u/house/rent/agentRentManage/getUserRentAsset\", \"request\": {\"pn\": \"pageNum\", \"ps\": \"pageSize\", \"default\": {}}, \"jumpText\": \"添加\", \"response\": {\"list\": \"records\"}, \"unloading\": true, \"itemModule\": {\"name\": \"assetListingItem\"}, \"multiFilter\": [{\"field\": \"pageNum\"}], \"itemNavigation\": \"\", \"multiFilterModule\": {\"name\": \"paginationFilter\"}}}, \"moduleContainer\": {}}",
        "createTime": "2022-09-06 14:00:54",
        	"extra":{
            "tags":"[{id:9},{id:10}]"
        },
        "id": "102",
        "jsonName": "1556929177066696705.json",
        "jsonPath": "jsonMock/DEFAULT/1556929177066696705.json",
        "pageDescrip": null,
        "pageId": "275478",
        "tagIds": null,
        "tags": null,
        "templateStatus": 0,
        "title": "房源上架",
        "updateTime": "2022-09-28 15:22:09"

      }


