server:
  port: 8080

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    # url: jdbc:mysql://192.168.3.16:3306/user_alliance?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false

    username: root
    password: root
    filters: log4j,wall,mergeStat
    sql-script-encoding: UTF-8
    schema: classpath*:sql/*-schema.sql
    data: classpath*:sql/*-data.sql
    initialize: false