@localHostEndpoint = http://localhost:8080
@reEndpoint = https://house.cloud.smallsaas.cn
@endpoint = {{localHostEndpoint}}

### 注：在windows下测试的时候 文件大小写不敏感 导致可能出现 输入appId default 如果存在 DEFAULT的文件 则会读取DEFAULT而不是新建个default文件
### 获取当前appId
GET {{endpoint}}/form/getAppId

### 设置appId
GET  {{endpoint}}/form/setAppId/test

### 获取当前appId 配置信息
GET {{endpoint}}/form/appMap

### 获取当前appId 下的id配置信息
GET {{endpoint}}/form/map

### 获取页面信息
GET {{endpoint}}/form?id=66666

### 提交页面信息
POST {{endpoint}}/form/66666
Content-Type: application/json

{  
    "version": "1",
    "name": "allOrder",
    "title": "订单",
    "pageStyle": {
    },
    "loadApi": "",
    "response": {
      "data":"data"
    },
    "request": {
    },
    "moduleContainer":{
    },
    "modules": [
      {
        "type": "autolist",
        "name":"",
        "key":"e59992z8-bb88-a788-9922-1623488775885",
        "container":{
            "height":"",
            "background":"#050E17"
        }
      }
    ],
    "moduleData": {
         "e59992z8-bb88-a788-9922-1623488775885": {
            "loadApi":"/api/u/order",
            "itemNavigation": "",
            "response":{
                "list":"records"
            },
            "request":{
                "default":{
                },
                "ps":"pageSize",
                "pn":"pageNum"
            },
            "itemModule":{
                "name":"orderItem"
            }
        }
    }
}



