server:
  port: 8080

spring:
  profiles:
    active: test

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.3.239:3306/cinema_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    #url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    filters: log4j,wall,mergeStat
    sql-script-encoding: UTF-8
    schema: classpath*:sql/*-schema.sql
    data: classpath*:sql/*-data.sql
    initialize: false

io:
  excel-template-dir: "excel-templates"
  excel-export-max-rows: 1000

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:power;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
    filters: log4j,wall,mergeStat
    schema: classpath*:h2/*-schema.sql
    data: classpath*:h2/*-data.sql

io:
  excel-template-dir: "excel-templates"
  excel-export-max-rows: 1000
