server:
  port: 8080

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

io:
  file-upload-path: "attachments"
  file-host: "attachments"
  bucket-app-id: "32791238237612378123"
  bucket-app-secret: "EF8WnIPlnDFYPEIt"
