server:
  port: 8080

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

io:
  fileUploadPath: "/attachments"
  fileHost: "/attachments"

bucket:
  appId:  "32791238237612378123"
  appSecret: "EF8WnIPlnDFYPEIt"