version: "3"
services:
  zero-io:
    image: zelejs/allin-web:jdk11
    privileged: true
    container_name: zero-io
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./io-api:/webapps
    environment:
      DL_STANDALONE: "zero-io-all-1.0.0-standalone.jar"

networks:
  default:
    external:
      name: ${network}
